name: Publish

on:
  release:
    types:
      - edited
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm packages
        run: yarn --frozen-lockfile

      - name: Build action
        run: yarn build

      - name: Publish action
        uses: JasonEtco/build-and-tag-action@v1
        with:
          setup: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
