name: Main workflow

on:
  - pull_request
  - push

jobs:
  asdf_is_installed:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup asdf
        uses: ./setup

      - name: asdf is available
        run: |
          echo ASDF_DIR=$ASDF_DIR
          echo ASDF_DATA_DIR=$ASDF_DATA_DIR
          echo PATH=$PATH
          asdf --version

  plugin_is_tested:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./plugin-test
        with:
          command: direnv --version
          plugin: direnv
          giturl: https://github.com/asdf-community/asdf-direnv.git
          gitref: master
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  plugins_are_installed:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./plugins-add
        with:
          tool_versions: |
            # tools wont be installed by this action, only plugins
            elixir foo
            nodejs bar
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          asdf plugin list --urls --refs | grep elixir
          asdf plugin list --urls --refs | grep nodejs

  installing-plugins-already-installed-are-skiped:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./setup

      - name: Add an asdf plugin
        run: |
          asdf plugin-add clusterctl git://github.com/pfnet-research/asdf-clusterctl.git

      - uses: ./plugins-add
        with:
          tool_versions: |
            # tools wont be installed by this action, only plugins
            elixir foo
            nodejs bar
            # plugins already installed are here
            clusterctl tako
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          asdf plugin list --urls --refs | grep elixir
          asdf plugin list --urls --refs | grep nodejs
          asdf plugin list --urls --refs | grep clusterctl

  tools_are_installed:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup asdf
        uses: ./install
        with:
          before_install: echo asdf nodejs import-keyring
          tool_versions: direnv 2.20.0

      - run: direnv version
