name: Main workflow

on:
  - pull_request
  - push

jobs:
  asdf_is_installed:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup asdf
        uses: ./setup

      - name: asdf is available
        run: |
          echo ASDF_DIR=$ASDF_DIR
          echo ASDF_DATA_DIR=$ASDF_DATA_DIR
          echo PATH=$PATH
          asdf --version

  plugin_is_tested:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./plugin-test
        with:
          command: direnv --version
          plugin: direnv
          giturl: https://github.com/asdf-community/asdf-direnv.git
          gitref: master
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  plugins_are_installed:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./plugins-add
        with:
          tool_versions: |
            # tools wont be installed by this action, only plugins
            elixir foo
            nodejs bar
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          asdf plugin list --urls --refs | grep elixir
          asdf plugin list --urls --refs | grep nodejs

  tools_are_installed:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup asdf
        uses: ./install
        with:
          before_install: echo asdf nodejs import-keyring
          tool_versions: direnv  2.20.0

      - run: direnv version

  publish:
    runs-on: ubuntu-latest

    needs:
      - asdf_is_installed
      - plugin_is_tested
      - plugins_are_installed
      - tools_are_installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install npm packages
        run: yarn --frozen-lockfile

      - name: Build action
        run: yarn build

      - name: Publish action
        if: contains(github.ref, 'refs/tags')
        uses: JasonEtco/build-and-tag-action@v1
        with:
          setup: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
